# Generated by Django 5.0.6 on 2024-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_posters/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Environmental Conservation', 'Environmental Conservation'), ('Community Development', 'Community Development'), ('Health and Wellness', 'Health and Wellness'), ('Education and Literacy', 'Education and Literacy'), ('Equality and Inclusion', 'Equality and Inclusion'), ('Animal Welfare', 'Animal Welfare'), ('Humanitarian Aid', 'Humanitarian Aid'), ('Sustainable Development', 'Sustainable Development'), ('Peace and Conflict Resolution', 'Peace and Conflict Resolution'), ('Digital Rights', 'Digital Rights'), ('Economic Empowerment', 'Economic Empowerment'), ('Policy Advocacy', 'Policy Advocacy'), ('Artistic Advocacy', 'Artistic Advocacy'), ('Other', 'Other')], default='Environmental Conservation', max_length=30),
        ),
    ]
