# Generated by Django 5.0.6 on 2025-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_donation_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_slides')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='motion_poster',
            field=models.FileField(blank=True, help_text='Short video/GIF (max 10-15 seconds)', null=True, upload_to='motion_posters'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='poster_slides',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='main.posterslide'),
        ),
    ]
