# Generated by Django 5.0.6 on 2025-01-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_affiliatelink_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/pp.png', max_length=255, upload_to='profile_pics/'),
        ),
    ]
