# Generated by Django 5.0.6 on 2024-08-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_campaign_poster_image_alter_campaign_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='poster_image',
            new_name='poster',
        ),
    ]
