# Generated by Django 5.0.6 on 2024-09-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_campaign_file_remove_campaignproduct_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='visible_to_followers',
        ),
    ]
