# Generated by Django 5.0.6 on 2025-06-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_activitycomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycomment',
            options={},
        ),
        migrations.AddField(
            model_name='activitycomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.activitycomment'),
        ),
    ]
