# Generated by Django 5.0.6 on 2024-08-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_poster_image_campaign_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='file',
        ),
    ]
