# Generated by Django 5.0.6 on 2024-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_campaign_visible_to_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='visible_to_followers',
            field=models.ManyToManyField(blank=True, related_name='visible_campaigns', to='main.profile'),
        ),
    ]
