# Generated by Django 5.0.6 on 2025-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_changemaker',
            field=models.BooleanField(default=False),
        ),
    ]
