# Generated by Django 5.0.6 on 2025-01-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_campaign_is_changemaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_changemaker',
        ),
    ]
