# Generated by Django 5.0.6 on 2025-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_campaign_poster_slides_posterslide_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='motion_poster',
        ),
        migrations.DeleteModel(
            name='PosterSlide',
        ),
    ]
