# Generated by Django 5.0.6 on 2025-01-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_campaign_is_changemaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='profile_verified',
        ),
    ]
