# Generated by Django 5.0.6 on 2025-07-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_campaign_motion_poster_delete_posterslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='GifImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gif_file', models.FileField(upload_to='gifs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
