# Generated by Django 5.0.6 on 2024-09-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_digital_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digital_Donation',
        ),
    ]
