# Generated by Django 5.0.6 on 2025-07-29 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_campaignfund_campaign_delete_gifimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payout_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested'), ('processing', 'Processing'), ('paid', 'Paid')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_details_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='flutterwave_subaccount_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Poverty and Hunger', 'Poverty and Hunger'), ('Clean Water and Sanitation', 'Clean Water and Sanitation'), ('Disaster Relief', 'Disaster Relief'), ('Healthcare and Medicine', 'Healthcare and Medicine'), ('Mental Health', 'Mental Health'), ('Human Rights and Equality', 'Human Rights and Equality'), ('Peace and Justice', 'Peace and Justice'), ('Education for All', 'Education for All'), ('Economic Empowerment', 'Economic Empowerment'), ('Climate Action', 'Climate Action'), ('Save Our Planet', 'Save Our Planet'), ('Tech for Humanity', 'Tech for Humanity'), ('Community Development', 'Community Development'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('flutterwave_response', models.JSONField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='main.campaign')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='main.campaign')),
            ],
        ),
    ]
