# Generated by Django 5.0.6 on 2025-02-14 09:16

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_message_image_message_link_message_voice_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='link',
        ),
        migrations.RemoveField(
            model_name='message',
            name='voice_note',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
