# Generated by Django 5.0.6 on 2025-07-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfee',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='payout_status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_details_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_iban',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_swift_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='flutterwave_subaccount_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Poverty and Hunger', 'Poverty and Hunger'), ('Clean Water and Sanitation', 'Clean Water and Sanitation'), ('Disaster Relief', 'Disaster Relief'), ('Healthcare and Medicine', 'Healthcare and Medicine'), ('Mental Health', 'Mental Health'), ('Human Rights and Equality', 'Human Rights and Equality'), ('Peace and Justice', 'Peace and Justice'), ('Education for All', 'Education for All'), ('Economic Empowerment', 'Economic Empowerment'), ('Climate Action', 'Climate Action'), ('Save Our Planet', 'Save Our Planet'), ('Tech for Humanity', 'Tech for Humanity'), ('Community Development', 'Community Development'), ('Other', 'Other')], default='Environmental Conservation', max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CampaignFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paypal_email', models.EmailField(default='paypal_email', max_length=254)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.DeleteModel(
            name='PlatformFee',
        ),
    ]
