# Generated by Django 5.0.6 on 2025-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_message_image_remove_message_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=models.TextField(),
        ),
    ]
