# Generated by Django 5.0.6 on 2025-07-30 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_platformfee_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfund',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignfund',
            name='paypal_email',
            field=models.EmailField(help_text="Campaign owner's PayPal email for receiving funds.", max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid PayPal email.')]),
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
    ]
