# Generated by Django 5.0.6 on 2025-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_campaign_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainstorming',
            name='idea',
            field=models.TextField(),
        ),
    ]
