# Generated by Django 5.0.6 on 2025-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_campaignfund_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfund',
            name='enable_donations',
            field=models.BooleanField(default=False),
        ),
    ]
