# Generated by Django 5.0.6 on 2025-02-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_brainstorming_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.campaign'),
        ),
    ]
