# Generated by Django 5.0.6 on 2025-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_campaignfund_enable_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfund',
            name='enable_donations',
        ),
        migrations.AddField(
            model_name='campaign',
            name='enable_donations',
            field=models.BooleanField(default=False),
        ),
    ]
