# Generated by Django 5.0.6 on 2025-07-31 07:12

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_campaign_enable_donations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfund',
            name='enable_donations',
        ),
        migrations.AlterUniqueTogether(
            name='supportcampaign',
            unique_together={('user', 'campaign')},
        ),
        migrations.AddField(
            model_name='supportcampaign',
            name='attend_event_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='brainstorm_idea_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='campaign_product_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='donate_monetary_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='supportcampaign',
            name='category',
        ),
    ]
