# Generated by Django 5.0.6 on 2025-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_campaignfund_enable_donations_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supportcampaign',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supportcampaign',
            name='category',
            field=models.CharField(choices=[(' Donate_monetary,', ' Donate_monetary,'), ('Brainstorming', 'Brainstorming'), ('CampaignProduct', 'CampaignProduct')], default='Monetary Donation', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='brainstorm_idea_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='campaign_product_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='donate_monetary_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='supportcampaign',
            name='attend_event_visible',
        ),
        migrations.RemoveField(
            model_name='supportcampaign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supportcampaign',
            name='updated_at',
        ),
    ]
