# Generated by Django 5.0.6 on 2025-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_campaignstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Information'), ('campaigns', 'Creating & Managing Campaigns'), ('funding', 'Funding & Payments'), ('security', 'Security & Policies'), ('backers', 'For Backers & Donors')], max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
