# Generated by Django 5.0.6 on 2025-07-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_supportcampaign_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcampaign',
            name='brainstorm_idea_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='campaign_product_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='donate_monetary_visible',
            field=models.BooleanField(default=False),
        ),
    ]
