# Generated by Django 5.0.6 on 2025-03-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in days. Leave blank for ongoing campaigns.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
