# Generated by Django 5.0.6 on 2025-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_campaign_duration_campaign_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('days', 'Days')], default='days', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Enter duration.', null=True),
        ),
    ]
