# Generated by Django 5.0.6 on 2025-03-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_campaign_duration_unit_alter_campaign_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='goal',
            new_name='target_amount',
        ),
    ]
