# Generated by Django 5.0.6 on 2025-07-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='payment_method',
        ),
    ]
