# Generated by Django 5.0.6 on 2025-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_pledge_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignfund',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='payoutrecord',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='supportcampaign',
            name='brainstorm_idea_visible',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Poverty and Hunger', 'Poverty and Hunger'), ('Clean Water and Sanitation', 'Clean Water and Sanitation'), ('Disaster Relief', 'Disaster Relief'), ('Healthcare and Medicine', 'Healthcare and Medicine'), ('Mental Health', 'Mental Health'), ('Human Rights and Equality', 'Human Rights and Equality'), ('Peace and Justice', 'Peace and Justice'), ('Education for All', 'Education for All'), ('Economic Empowerment', 'Economic Empowerment'), ('Climate Action', 'Climate Action'), ('Wildlife and Conservation', 'Wildlife and Conservation'), ('Tech for Humanity', 'Tech for Humanity'), ('Community Development', 'Community Development'), ('Arts and Culture', 'Arts and Culture'), ('Other', 'Other')], default='Education for All', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportcampaign',
            name='category',
            field=models.CharField(choices=[(' Donate_monetary,', ' Donate_monetary,'), ('CampaignProduct', 'CampaignProduct')], default='Monetary Donation', max_length=50),
        ),
        migrations.DeleteModel(
            name='Brainstorming',
        ),
        migrations.DeleteModel(
            name='CampaignFund',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='PayoutRecord',
        ),
    ]
