# Generated by Django 5.0.6 on 2025-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_goal_campaign_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('RallyNex-Led', 'RallyNex-Led'), ('Tips', 'Tips'), ('Spotlight', 'Spotlight'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='estimated_reading_time',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='campaignfund',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
