# Generated by Django 5.0.6 on 2025-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_message_file_message_file_name_message_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
