# Generated by Django 5.0.6 on 2025-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_commentlike_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.TextField(blank=True, help_text='Comma-separated list of phone numbers/emails', null=True),
        ),
        migrations.AlterField(
            model_name='campaignfund',
            name='paypal_email',
            field=models.EmailField(default='paypal_email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaignfund',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
