# Generated by Django 5.0.6 on 2025-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_supportcampaign_pledge_visible_alter_pledge_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='contact',
        ),
        migrations.AddField(
            model_name='donation',
            name='destination',
            field=models.CharField(choices=[('campaign', 'Campaign Owner'), ('site', 'Site Tip')], default='campaign', max_length=10),
        ),
    ]
