# Generated by Django 5.0.6 on 2025-09-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='campaignproduct',
            name='url',
        ),
    ]
