# Generated by Django 5.0.6 on 2025-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_campaignproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('preorder', 'Preorder'), ('discontinued', 'Discontinued')], default='in_stock', max_length=20),
        ),
    ]
