# Generated by Django 5.0.6 on 2025-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_campaignproduct_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
