# Generated by Django 5.0.6 on 2025-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_pledge_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funding_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional target amount. Leave empty if no funding goal.', max_digits=10, null=True),
        ),
    ]
