# Generated by Django 5.0.6 on 2025-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_campaign_funding_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
