# Generated by Django 5.0.6 on 2025-09-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_profile_flutterwave_subaccount_id_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flutterwave_tx_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign_owner_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_owner_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pledge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_transaction', to='main.pledge')),
            ],
        ),
    ]
