# Generated by Django 5.0.6 on 2025-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_donation_campaign_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='campaign_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='flutterwave_transaction_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='platform_fee',
        ),
        migrations.AlterField(
            model_name='donation',
            name='fulfilled',
            field=models.BooleanField(default=True),
        ),
    ]
