# Generated by Django 5.0.6 on 2025-09-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_donation_campaign_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='destination',
        ),
    ]
