# Generated by Django 5.0.6 on 2025-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_donation_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
