# Generated by Django 5.0.6 on 2025-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_donation_tx_ref_alter_donation_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
