# Generated by Django 5.0.6 on 2025-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_pledge_anonymous_name_alter_pledge_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='tx_ref',
        ),
        migrations.AddField(
            model_name='pledge',
            name='flw_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='tx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PledgeTransaction',
        ),
    ]
