# Generated by Django 5.0.6 on 2025-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_pledge_tx_ref_pledge_flw_ref_pledge_tx_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='flw_ref',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='tx_id',
        ),
        migrations.AddField(
            model_name='pledge',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
