# Generated by Django 5.0.6 on 2025-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_pledge_flw_ref_remove_pledge_tx_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], default='bank', max_length=20),
        ),
    ]
