# Generated by Django 5.0.6 on 2025-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_profile_account_bank_profile_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile_money_provider',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_money_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='profile',
            name='subaccount_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
