# Generated by Django 5.0.6 on 2025-09-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_notification_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_bank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='flutterwave_subaccount_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subaccount_message',
        ),
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
