# Generated by Django 5.0.6 on 2025-09-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_profile_account_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='tx_ref',
            new_name='paypal_order_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
