# Generated by Django 5.0.6 on 2025-09-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_tx_ref_donation_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='paypal_payout_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign_owner_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_payout_batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='site_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
