# Generated by Django 5.0.6 on 2025-09-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_donation_paypal_payout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='campaign_owner_share',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='paypal_payout_batch_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='site_share',
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='main.campaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
