# Generated by Django 5.0.6 on 2025-09-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_donation_campaign_owner_share_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='tx_ref',
            new_name='paypal_order_id',
        ),
        migrations.AddField(
            model_name='pledge',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pledge',
            name='paypal_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
