# Generated by Django 5.0.6 on 2025-09-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_rename_tx_ref_pledge_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
