# Generated by Django 5.0.6 on 2025-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_pledge_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending Payout'), ('processing', 'Processing Payout'), ('completed', 'Payout Completed'), ('failed', 'Payout Failed'), ('no_email', 'No PayPal Email')], default='pending', max_length=20),
        ),
    ]
