# Generated by Django 5.0.6 on 2025-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_pledge_payout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='payout_status',
        ),
    ]
