# Generated by Django 5.0.6 on 2025-09-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_pledge_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('paypal_email', models.EmailField(max_length=254)),
                ('paypal_batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='main.profile')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='main.transaction')),
            ],
        ),
    ]
