# Generated by Django 5.0.6 on 2025-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_transaction_owner_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paypal_capture_id',
            new_name='payout_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='platform_fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
